### ISSUE TITLE
I don't understand how to set the parent of a page?

### ISSUE THREAD

**Issue by innerdaze** [kasperisager/docpad-plugin-tree#2]
I'm probably getting this completely wrong, but what I assumed this was doing was converting a nested directory of documents into a JSON structure. However the JSON structure doesn't fit this way of thinking as it portrays documents as direct children of documents.

Therefore I don't understand how your plugin is determining which document becomes the parent of  and sub-documents. Is there a "parent" config i can specify on a per document level?

**Comment by kasperisager** [comment]
The plugin does indeed assume that documents are children of other documents. Given a root document (say `/`), all documents directly below this root (`/fst`, `/snd`, etc.) become children of said root.
